/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinterRouteImport } from './routes/winter'
import { Route as SummerRouteImport } from './routes/summer'
import { Route as StayRouteImport } from './routes/stay'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ExplorationRouteImport } from './routes/exploration'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const WinterRoute = WinterRouteImport.update({
  id: '/winter',
  path: '/winter',
  getParentRoute: () => rootRouteImport,
} as any)
const SummerRoute = SummerRouteImport.update({
  id: '/summer',
  path: '/summer',
  getParentRoute: () => rootRouteImport,
} as any)
const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorationRoute = ExplorationRouteImport.update({
  id: '/exploration',
  path: '/exploration',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/exploration': typeof ExplorationRoute
  '/journal': typeof JournalRoute
  '/prices': typeof PricesRoute
  '/stay': typeof StayRoute
  '/summer': typeof SummerRoute
  '/winter': typeof WinterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/exploration': typeof ExplorationRoute
  '/journal': typeof JournalRoute
  '/prices': typeof PricesRoute
  '/stay': typeof StayRoute
  '/summer': typeof SummerRoute
  '/winter': typeof WinterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/exploration': typeof ExplorationRoute
  '/journal': typeof JournalRoute
  '/prices': typeof PricesRoute
  '/stay': typeof StayRoute
  '/summer': typeof SummerRoute
  '/winter': typeof WinterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/exploration'
    | '/journal'
    | '/prices'
    | '/stay'
    | '/summer'
    | '/winter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/exploration'
    | '/journal'
    | '/prices'
    | '/stay'
    | '/summer'
    | '/winter'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/exploration'
    | '/journal'
    | '/prices'
    | '/stay'
    | '/summer'
    | '/winter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ExplorationRoute: typeof ExplorationRoute
  JournalRoute: typeof JournalRoute
  PricesRoute: typeof PricesRoute
  StayRoute: typeof StayRoute
  SummerRoute: typeof SummerRoute
  WinterRoute: typeof WinterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winter': {
      id: '/winter'
      path: '/winter'
      fullPath: '/winter'
      preLoaderRoute: typeof WinterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summer': {
      id: '/summer'
      path: '/summer'
      fullPath: '/summer'
      preLoaderRoute: typeof SummerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exploration': {
      id: '/exploration'
      path: '/exploration'
      fullPath: '/exploration'
      preLoaderRoute: typeof ExplorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ExplorationRoute: ExplorationRoute,
  JournalRoute: JournalRoute,
  PricesRoute: PricesRoute,
  StayRoute: StayRoute,
  SummerRoute: SummerRoute,
  WinterRoute: WinterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
